[package]
name = "res-nats"
description = "NATS resource provider"
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
nkeys = { version = "0.4.5" }
runtime.workspace = true
tracing.workspace = true
