[package]
name = "runtime"
description = "Wasm runtime"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["jit"]
# Enables just-in-time wasm to machine code compilation.
jit = ["wasmtime/cranelift"]

[dependencies]
anyhow.workspace = true
cfg-if.workspace = true
clap = { version = "4.5.48", features = ["derive"] }
credibil-otel.workspace = true
futures.workspace = true
tokio = { workspace = true, features = ["signal"] }
tracing.workspace = true
wasmtime = { workspace = true, features = ["runtime"] }
wasmtime-wasi.workspace = true
wasmtime-wasi-http.workspace = true

# required for azure_identity, etc.
openssl = { version = "0.10", features = ["vendored"] }

[package.metadata.cargo-machete]
ignored = ["openssl"]

[workspace]
members = ["crates/*", "examples/guests/*", "examples/runtimes/*", "examples/services/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
edition = "2024"
homepage = "https://credibil.io"
keywords = ["decentralized", "identity"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/credibil/wrt"
rust-version = "1.90"
version = "0.5.0"

[workspace.lints.rust]
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
all = "warn"
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
anyhow = "1.0.100"
async-nats = { version = "0.42.0" }
axum = { version = "0.8.4", default-features = false }                                            # features = ["form", "json", "query", "tracing"]
azure_core = { version = "0.27.0", default-features = false, features = ["reqwest_rustls"] }
azure_identity = { version = "0.27.0", default-features = false }
azure_security_keyvault_secrets = { version = "0.6.0", default-features = false }
base64ct = { version = "1.8.0", features = ["std"] }
bytes = "1.10.1"
cfg-if = "1.0.3"
chrono = "0.4.42"
credibil-encoding = { git = "https://github.com/credibil/core.git", tag = "v0.1.0" }
credibil-otel = { git = "https://github.com/credibil/core.git", tag = "v0.1.0" }
futures = "0.3.31"
http = "1.3.1"
mongodb = { version = "3.3.0" }
opentelemetry = "0.30.0"
opentelemetry_sdk = { version = "0.30.0", features = ["experimental_metrics_custom_reader"] }
runtime = { path = "." }
sdk-http = { path = "crates/sdk-http" }
sdk-otel = { path = "crates/sdk-otel" }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
time = "0.3.44"
tokio = { version = "1.47.1", default-features = false }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.31.0"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
wasi = "0.14.7"
wasmtime = { version = "37.0.0", default-features = false, features = ["component-model-async"] }
wasmtime-wasi = { version = "37.0.0", features = ["p3"] }
wasmtime-wasi-http = { version = "37.0.0", features = ["p3"] }
wasmtime-wasi-io = "37.0.0"
wit-bindgen = "0.46.0"
wit-bindings = { path = "crates/wit-bindings" }

res-azkeyvault = { path = "examples/services/res-azkeyvault" }
res-mongodb = { path = "examples/services/res-mongodb" }
res-nats = { path = "examples/services/res-nats" }
wasi-blobstore-mdb = { path = "examples/services/wasi-blobstore-mdb" }
wasi-http = { path = "crates/wasi-http" }
wasi-keyvalue-nats = { path = "examples/services/wasi-keyvalue-nats" }
wasi-messaging-nats = { path = "examples/services/wasi-messaging-nats" }
wasi-otel = { path = "crates/wasi-otel" }
wasi-vault-az = { path = "examples/services/wasi-vault-az" }

# [patch."https://github.com/credibil/core.git"]
# credibil-otel = { path = "../../credibil/core/crates/otel" }
