# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html

[graph]
targets = [
  "aarch64-apple-darwin",
  "wasm32-wasip2",
]
all-features = true

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "allow"
deny = [
  { name = "tokio", deny-multiple-versions = true },
]
skip = [
  { crate = "wit-bindgen", reason = "duplicate versions" },
]
skip-tree = [
  { crate = "async-nats", depth = 5, reason = "contains out of date versions" },
  { crate = "wasmtime-wasi", depth = 5, reason = "contains out of date versions" },
  { name = "mongodb", reason = "false positive" },
]

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"
