[toolchain]
# channel = "nightly"
channel = "stable"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "nightly-aarch64-apple-darwin"
  "aarch64-apple-darwin",
  "wasm32-wasip2",
]
# profile = "minimal" # "default"
