[package]
name = "res-mongodb"
description = "MongoDB resource provider"
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
mongodb.workspace = true
runtime.workspace = true
tracing.workspace = true
