[package]
name = "http-out-ex"
description = "Example wasm guest making outbound HTTP request"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
http.workspace = true
sdk-http.workspace = true
serde_json.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
