[package]
name = "otel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["json"] }
opentelemetry.workspace = true
sdk-http.workspace = true
sdk-otel = { workspace = true, features = ["guest-export"] }
serde_json.workspace = true
tracing.workspace = true
wasi.workspace = true
