[package]
name = "wasi-keyvalue-nats"
description = "WASI Keyvalue WIT implementation using NATS"
edition.workspace = true
publish = false

[lints]
workspace = true

[features]

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
base64ct.workspace = true
futures.workspace = true
runtime.workspace = true
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
