[package]
name = "wasi-vault-az"
description = "WASI Vault WIT implementation using Azure Key Vault"
edition.workspace = true
publish = false

[lints]
workspace = true

[features]

[dependencies]
anyhow.workspace = true
azure_security_keyvault_secrets.workspace = true
base64ct.workspace = true
futures.workspace = true
http.workspace = true
runtime.workspace = true
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
