[package]
name = "wasi-blobstore-mdb"
description = "WASI blobstore WIT implementation using mongodb"
edition.workspace = true
publish = false

[lints]
workspace = true

[features]

[dependencies]
anyhow.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
mongodb.workspace = true
runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
