[package]
name = "res-azkeyvault"
description = "Azure Key Vault resource provider"
edition.workspace = true
publish = false

[lib]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
azure_core.workspace = true
azure_identity.workspace = true
azure_security_keyvault_secrets.workspace = true
runtime.workspace = true
tracing.workspace = true
