[package]
name = "compiler"
description = "Wasm guest compiler example"
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
runtime = { workspace = true, features = ["jit"] }
tokio.workspace = true
