[package]
name = "pub-sub"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["json", "macros"] }
bytes.workspace = true
sdk-http.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wit-bindgen.workspace = true
wit-bindings.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }