
services:
  otel:
    image: ghcr.io/credibil/tempo
    env_file: .env
    ports:
      - 8080:8080
    command: ["/otel.wasm"]
    volumes:
       - ./../../target/wasm32-wasip2/release/otel.wasm:/otel.wasm
    depends_on:
      - otelcol

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317
      - 4318:4318
    depends_on:
      - jaeger
      - prometheus
      
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-remote-write-receiver
      # - --log.level=debug

  nats:
    image: nats:latest
    platform: linux/arm64
    ports:
      - 4222:4222
    command: ["-js"]