[package]
name = "everything"
description = "Runtime with all services"
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
res-azkeyvault.workspace = true
res-mongodb.workspace = true
res-nats.workspace = true
runtime.workspace = true
tokio.workspace = true
wasi-blobstore-mdb.workspace = true
wasi-http.workspace = true
wasi-keyvalue-nats.workspace = true
wasi-messaging-nats.workspace = true
wasi-otel.workspace = true
wasi-vault-az.workspace = true
