[package]
name = "keyvalue-ex"
description = "Example wasm guest using wasi:keyvalue"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum = { workspace = true, features = ["json"] }
bytes.workspace = true
sdk-http.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
wit-bindings.workspace = true
