[package]
name = "otel-ex"
description = "Example wasm guest using wasi:otel and OpenTelemetry"
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
axum.workspace = true
http.workspace = true
opentelemetry.workspace = true
sdk-http.workspace = true
sdk-otel = { workspace = true, features = ["guest-export"] }
serde_json.workspace = true
tower-http.workspace = true
tracing.workspace = true
wasi.workspace = true
