[package]
name = "http"
description = "Example guest component using wasi-http"
# version = "0.1.0"
publish = false

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
axum = { workspace = true, features = ["json"] }
sdk-http.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasi.workspace = true
