name: Publish Release

on:
  workflow_dispatch:

jobs:
  skip:
    name: Skipped
    if: ${{ !startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow only runs on the 'release-*' branches"
          exit 1

  # ci:
  #   name: CI
  #   if: ${{ startsWith(github.ref_name, 'release-') }}
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main
  #   secrets: inherit
  #   with:
  #     outdated: prost

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # crates:
  #   name: Publish crates
  #   needs: publish
  #   uses: credibil/pipeline/.github/workflows/crates.yaml@main
  #   secrets: inherit

  package:
    name: Package
    # needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./examples/runtimes/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            PACKAGE=everything
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.publish.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
