name: Publish Release

on:
  workflow_dispatch:

jobs:
  # publish:
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main
  publish:
    name: Publish
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - run: echo "ghcr.io/${{ github.event.repository.name }}"
        
      - name: Version
        id: version
        run: echo "version=0.1.0" >> $GITHUB_OUTPUT

  package:
    name: Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: publish
    
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./examples/runtimes/Dockerfile
          build-args: |
            PACKAGE=tempo-all
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.publish.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest